blog/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from . import views

__author__ = "suvorovao"


app_name = 'blog'
urlpatterns = [
    path('', views.posts, name='posts'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('drafts/', views.post_draft_list, name='post_draft_list'),
    path('post/<pk>/publish', views.post_publish, name='post_publish'),
    path('post/<pk>/remove/', views.post_remove, name='post_remove'),
    path('post/<int:pk>/comment', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:pk>/approve', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove', views.comment_remove, name='comment_remove'),
]

mydj/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='poll_detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='poll_results'),
    path('<int:question_id>/vote/', views.poll_vote, name='poll_vote'),
]

polls/models.py
from django.db import models
from django.utils import timezone
from datetime import timedelta


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def recently_published(self):
        now = timezone.now()
        return now - timedelta(days=1) <= self.pub_date <= now

    recently_published.admin_order_field = 'pub_date'
    recently_published.boolean = True
    recently_published.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect

# two variants to load views and errors
# from django.http import HttpResponse, Http404
# from django.template import loader
# from django.utils.translation import gettext as _
from django.utils import timezone
from django.urls import reverse
from django.views import generic
from django.db.models import F
from .models import Question, Choice


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set
        to be published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     template = loader.get_template('polls/index.html')
#     context = {'latest_question_list': latest_question_list}
#     return HttpResponse(template.render(context, request))


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/poll_detail.html'

    def get_queryset(self):
        """ Excludes any questions that aren't published yet."""
        return Question.objects.filter(pub_date__lte=timezone.now())


# def poll_detail(request, question_id):
#     try:
#         question = Question.objects.get(pk=question_id)
#     except Question.DoesNotExist:
#         raise Http404(_("Question does not exist."))
#     return render(request, 'polls/poll_detail.html', {'question': question})


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/poll_results.html'


# def poll_results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/poll_results.html', {'question': question})


def poll_vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/poll_detail.html', {'question': question,
                                                          'Error_message': "You didn't select a choice."})
    else:
        selected_choice.votes = F('votes') + 1
        selected_choice.save()
    return HttpResponseRedirect(reverse('polls:poll_results', args=(question.id,)))

polls/templates/polls/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>ManoolK | Polls</title>

        <link href="https://fonts.googleapis.com/css?family=Montserrat&subset=latin,cyrillic" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Roboto&subset=latin,cyrillic" rel="stylesheet" type="text/css">

<!--        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">-->
<!--        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">-->
        <link rel="stylesheet" href="{% static 'polls/css/polls.css' %}">
    </head>
<body>
<header class="page-header">
    <h1 class="heading-primary"><a href="{% url 'polls:index' %}">ManoolK Polls</a></h1>
</header>
<div class="content container">
    <div class="row">
        <div class="col-md-8">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content %}

{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:poll_detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}
{% endblock %}

polls/templates/polls/poll_detail.html
{% extends 'polls/base.html' %}

{% block content %}

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:poll_vote' question.id %}" method="post">{% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
<input type="submit" value="Vote">
</form>

{% endblock %}

polls/templates/polls/poll_results.html
{% extends 'polls/base.html' %}

{% block content %}

<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>
<a href="{% url 'polls:poll_detail' question.id %}">Vote again?</a>

{% endblock %}